=== nwsj2008/opinion/bin/OpinionXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/OpinionXMLSchema" xmlns:opinion="http://www.example.org/OpinionXMLSchema" elementFormDefault="qualified">
   <xsd:element name="items">  
      <xsd:complexType>        
         <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="description" type="xsd:string"/>
            <xsd:element name="para" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType >
                  <xsd:sequence>
                     <xsd:element name="para_name" type="xsd:string"/>
                     <xsd:element name="para_value" type="xsd:string"/>
                     <xsd:element name="para_description" type="xsd:string"/>
                  </xsd:sequence> 
               </xsd:complexType>      
            </xsd:element>         
         </xsd:sequence>
      </xsd:complexType>     
   </xsd:element>
</xsd:schema>

=== nwsj2008/opinion/bin/forecast.xml
<?xml version="1.0" encoding="UTF-8"?>
<opinion:items xmlns:opinion="http://www.example.org/OpinionXMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/OpinionXMLSchema OpinionXMLSchema.xsd">
	<opinion:name>forecast</opinion:name>
	<opinion:description>parameters of forecast</opinion:description>
	<opinion:para>
		<opinion:para_name>minTimePeriod</opinion:para_name>
		<opinion:para_value>40</opinion:para_value>
		<opinion:para_description>
			minimum number of observation period
		</opinion:para_description>
	</opinion:para>
	<opinion:para>
		<opinion:para_name>forecastPeriod</opinion:para_name>
		<opinion:para_value>10</opinion:para_value>
		<opinion:para_description>
			number of forecast period
		</opinion:para_description>
	</opinion:para>
	<opinion:para>
		<opinion:para_name>observPeriod</opinion:para_name>
		<opinion:para_value>0</opinion:para_value>
		<opinion:para_description>
			number of observation period used to compare
		</opinion:para_description>
	</opinion:para>
	<opinion:para>
		<opinion:para_name>overTime</opinion:para_name>
		<opinion:para_value>600000</opinion:para_value>
		<opinion:para_description>
			forecast calculation over time
		</opinion:para_description>
	</opinion:para>
	<opinion:para>
		<opinion:para_name>forecastPath</opinion:para_name>
		<opinion:para_value>E:\\opinionImg\\</opinion:para_value>
		<opinion:para_description>
			the path which the forecast data put in
		</opinion:para_description>
	</opinion:para>
	<opinion:para>
		<opinion:para_name>forecastPicPath</opinion:para_name>
		<opinion:para_value>/opinionImg/</opinion:para_value>
		<opinion:para_description>
			the path where to get the forecast data
		</opinion:para_description>
	</opinion:para>
	<opinion:para>
		<opinion:para_name>noPicPathString</opinion:para_name>
		<opinion:para_value>noforecast.png</opinion:para_value>
		<opinion:para_description>
			the picture of the cluster which can't be forecasted
		</opinion:para_description>
	</opinion:para>
</opinion:items>
